//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquestionGame.Presentation.WinForm.ConquestionServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class Game : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game.GameStatusEnum GameStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoOfRoundsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player[] PlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet QuestionSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round[] RoundsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game.GameStatusEnum GameStatus {
            get {
                return this.GameStatusField;
            }
            set {
                if ((this.GameStatusField.Equals(value) != true)) {
                    this.GameStatusField = value;
                    this.RaisePropertyChanged("GameStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoOfRounds {
            get {
                return this.NoOfRoundsField;
            }
            set {
                if ((this.NoOfRoundsField.Equals(value) != true)) {
                    this.NoOfRoundsField = value;
                    this.RaisePropertyChanged("NoOfRounds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player[] Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet QuestionSet {
            get {
                return this.QuestionSetField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionSetField, value) != true)) {
                    this.QuestionSetField = value;
                    this.RaisePropertyChanged("QuestionSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round[] Rounds {
            get {
                return this.RoundsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoundsField, value) != true)) {
                    this.RoundsField = value;
                    this.RaisePropertyChanged("Rounds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Game.GameStatusEnum", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
        public enum GameStatusEnum : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            starting = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ongoing = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            finished = 2,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionSet", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class QuestionSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Question[] QuestionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Question[] Questions {
            get {
                return this.QuestionsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionsField, value) != true)) {
                    this.QuestionsField = value;
                    this.RaisePropertyChanged("Questions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Round", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class Round : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquestionGame.Presentation.WinForm.ConquestionServiceReference.PlayerAnswer[] PlayerAnswersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Question QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime QuestionStartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoundNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player RoundWinnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.PlayerAnswer[] PlayerAnswers {
            get {
                return this.PlayerAnswersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerAnswersField, value) != true)) {
                    this.PlayerAnswersField = value;
                    this.RaisePropertyChanged("PlayerAnswers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Question Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime QuestionStartTime {
            get {
                return this.QuestionStartTimeField;
            }
            set {
                if ((this.QuestionStartTimeField.Equals(value) != true)) {
                    this.QuestionStartTimeField = value;
                    this.RaisePropertyChanged("QuestionStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoundNo {
            get {
                return this.RoundNoField;
            }
            set {
                if ((this.RoundNoField.Equals(value) != true)) {
                    this.RoundNoField = value;
                    this.RaisePropertyChanged("RoundNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player RoundWinner {
            get {
                return this.RoundWinnerField;
            }
            set {
                if ((object.ReferenceEquals(this.RoundWinnerField, value) != true)) {
                    this.RoundWinnerField = value;
                    this.RaisePropertyChanged("RoundWinner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Answer[] AnswersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Answer[] Answers {
            get {
                return this.AnswersField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswersField, value) != true)) {
                    this.AnswersField = value;
                    this.RaisePropertyChanged("Answers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Answer", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class Answer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerAnswer", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class PlayerAnswer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Answer AnswerGivenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player PlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PlayerAnswerTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Answer AnswerGiven {
            get {
                return this.AnswerGivenField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerGivenField, value) != true)) {
                    this.AnswerGivenField = value;
                    this.RaisePropertyChanged("AnswerGiven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player Player {
            get {
                return this.PlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerField, value) != true)) {
                    this.PlayerField = value;
                    this.RaisePropertyChanged("Player");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PlayerAnswerTime {
            get {
                return this.PlayerAnswerTimeField;
            }
            set {
                if ((this.PlayerAnswerTimeField.Equals(value) != true)) {
                    this.PlayerAnswerTimeField = value;
                    this.RaisePropertyChanged("PlayerAnswerTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConquestionServiceReference.IConquestionService")]
    public interface IConquestionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CreatePlayer", ReplyAction="http://tempuri.org/IConquestionService/CreatePlayerResponse")]
        ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player CreatePlayer(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CreatePlayer", ReplyAction="http://tempuri.org/IConquestionService/CreatePlayerResponse")]
        System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player> CreatePlayerAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrievePlayer", ReplyAction="http://tempuri.org/IConquestionService/RetrievePlayerResponse")]
        ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player RetrievePlayer(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrievePlayer", ReplyAction="http://tempuri.org/IConquestionService/RetrievePlayerResponse")]
        System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player> RetrievePlayerAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CreateGame", ReplyAction="http://tempuri.org/IConquestionService/CreateGameResponse")]
        void CreateGame(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CreateGame", ReplyAction="http://tempuri.org/IConquestionService/CreateGameResponse")]
        System.Threading.Tasks.Task CreateGameAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CreateGame2", ReplyAction="http://tempuri.org/IConquestionService/CreateGame2Response")]
        void CreateGame2(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, string questionSet, int noOfRounds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CreateGame2", ReplyAction="http://tempuri.org/IConquestionService/CreateGame2Response")]
        System.Threading.Tasks.Task CreateGame2Async(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, string questionSet, int noOfRounds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/AddPlayer", ReplyAction="http://tempuri.org/IConquestionService/AddPlayerResponse")]
        void AddPlayer(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/AddPlayer", ReplyAction="http://tempuri.org/IConquestionService/AddPlayerResponse")]
        System.Threading.Tasks.Task AddPlayerAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/ActiveGames", ReplyAction="http://tempuri.org/IConquestionService/ActiveGamesResponse")]
        ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game[] ActiveGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/ActiveGames", ReplyAction="http://tempuri.org/IConquestionService/ActiveGamesResponse")]
        System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game[]> ActiveGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/ChooseGame", ReplyAction="http://tempuri.org/IConquestionService/ChooseGameResponse")]
        ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game ChooseGame(string name, bool retrieveAssociation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/ChooseGame", ReplyAction="http://tempuri.org/IConquestionService/ChooseGameResponse")]
        System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game> ChooseGameAsync(string name, bool retrieveAssociation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/JoinGame", ReplyAction="http://tempuri.org/IConquestionService/JoinGameResponse")]
        bool JoinGame(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/JoinGame", ReplyAction="http://tempuri.org/IConquestionService/JoinGameResponse")]
        System.Threading.Tasks.Task<bool> JoinGameAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/LeaveGame", ReplyAction="http://tempuri.org/IConquestionService/LeaveGameResponse")]
        bool LeaveGame(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/LeaveGame", ReplyAction="http://tempuri.org/IConquestionService/LeaveGameResponse")]
        System.Threading.Tasks.Task<bool> LeaveGameAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrieveAllPlayersByGameId", ReplyAction="http://tempuri.org/IConquestionService/RetrieveAllPlayersByGameIdResponse")]
        ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player[] RetrieveAllPlayersByGameId(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrieveAllPlayersByGameId", ReplyAction="http://tempuri.org/IConquestionService/RetrieveAllPlayersByGameIdResponse")]
        System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player[]> RetrieveAllPlayersByGameIdAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/StartGame", ReplyAction="http://tempuri.org/IConquestionService/StartGameResponse")]
        bool StartGame(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/StartGame", ReplyAction="http://tempuri.org/IConquestionService/StartGameResponse")]
        System.Threading.Tasks.Task<bool> StartGameAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/AddQuestionSet", ReplyAction="http://tempuri.org/IConquestionService/AddQuestionSetResponse")]
        void AddQuestionSet(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet questionSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/AddQuestionSet", ReplyAction="http://tempuri.org/IConquestionService/AddQuestionSetResponse")]
        System.Threading.Tasks.Task AddQuestionSetAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet questionSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CheckIfGameIsFinished", ReplyAction="http://tempuri.org/IConquestionService/CheckIfGameIsFinishedResponse")]
        bool CheckIfGameIsFinished(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CheckIfGameIsFinished", ReplyAction="http://tempuri.org/IConquestionService/CheckIfGameIsFinishedResponse")]
        System.Threading.Tasks.Task<bool> CheckIfGameIsFinishedAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrieveAllQuestionSets", ReplyAction="http://tempuri.org/IConquestionService/RetrieveAllQuestionSetsResponse")]
        ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet[] RetrieveAllQuestionSets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrieveAllQuestionSets", ReplyAction="http://tempuri.org/IConquestionService/RetrieveAllQuestionSetsResponse")]
        System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet[]> RetrieveAllQuestionSetsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrieveQuestionSet", ReplyAction="http://tempuri.org/IConquestionService/RetrieveQuestionSetResponse")]
        ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet RetrieveQuestionSet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrieveQuestionSet", ReplyAction="http://tempuri.org/IConquestionService/RetrieveQuestionSetResponse")]
        System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet> RetrieveQuestionSetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrieveQuestionSetByTitle", ReplyAction="http://tempuri.org/IConquestionService/RetrieveQuestionSetByTitleResponse")]
        ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet RetrieveQuestionSetByTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrieveQuestionSetByTitle", ReplyAction="http://tempuri.org/IConquestionService/RetrieveQuestionSetByTitleResponse")]
        System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet> RetrieveQuestionSetByTitleAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/ValidateAnswer", ReplyAction="http://tempuri.org/IConquestionService/ValidateAnswerResponse")]
        bool ValidateAnswer(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Answer answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/ValidateAnswer", ReplyAction="http://tempuri.org/IConquestionService/ValidateAnswerResponse")]
        System.Threading.Tasks.Task<bool> ValidateAnswerAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Answer answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CheckPlayerAnswers", ReplyAction="http://tempuri.org/IConquestionService/CheckPlayerAnswersResponse")]
        bool CheckPlayerAnswers(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CheckPlayerAnswers", ReplyAction="http://tempuri.org/IConquestionService/CheckPlayerAnswersResponse")]
        System.Threading.Tasks.Task<bool> CheckPlayerAnswersAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/SubmitAnswer", ReplyAction="http://tempuri.org/IConquestionService/SubmitAnswerResponse")]
        void SubmitAnswer(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.PlayerAnswer playerAnswer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/SubmitAnswer", ReplyAction="http://tempuri.org/IConquestionService/SubmitAnswerResponse")]
        System.Threading.Tasks.Task SubmitAnswerAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.PlayerAnswer playerAnswer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CheckIfAllPlayersAnswered", ReplyAction="http://tempuri.org/IConquestionService/CheckIfAllPlayersAnsweredResponse")]
        bool CheckIfAllPlayersAnswered(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CheckIfAllPlayersAnswered", ReplyAction="http://tempuri.org/IConquestionService/CheckIfAllPlayersAnsweredResponse")]
        System.Threading.Tasks.Task<bool> CheckIfAllPlayersAnsweredAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CreateRound", ReplyAction="http://tempuri.org/IConquestionService/CreateRoundResponse")]
        void CreateRound(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CreateRound", ReplyAction="http://tempuri.org/IConquestionService/CreateRoundResponse")]
        System.Threading.Tasks.Task CreateRoundAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/GetRoundWinner", ReplyAction="http://tempuri.org/IConquestionService/GetRoundWinnerResponse")]
        ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player GetRoundWinner(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/GetRoundWinner", ReplyAction="http://tempuri.org/IConquestionService/GetRoundWinnerResponse")]
        System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player> GetRoundWinnerAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/GetRandomQuestion", ReplyAction="http://tempuri.org/IConquestionService/GetRandomQuestionResponse")]
        ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Question GetRandomQuestion(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/GetRandomQuestion", ReplyAction="http://tempuri.org/IConquestionService/GetRandomQuestionResponse")]
        System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Question> GetRandomQuestionAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/DetermineGameWinner", ReplyAction="http://tempuri.org/IConquestionService/DetermineGameWinnerResponse")]
        ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player DetermineGameWinner(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/DetermineGameWinner", ReplyAction="http://tempuri.org/IConquestionService/DetermineGameWinnerResponse")]
        System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player> DetermineGameWinnerAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/DetermineNoOfCorrectAnswers", ReplyAction="http://tempuri.org/IConquestionService/DetermineNoOfCorrectAnswersResponse")]
        int DetermineNoOfCorrectAnswers(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/DetermineNoOfCorrectAnswers", ReplyAction="http://tempuri.org/IConquestionService/DetermineNoOfCorrectAnswersResponse")]
        System.Threading.Tasks.Task<int> DetermineNoOfCorrectAnswersAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConquestionServiceChannel : ConquestionGame.Presentation.WinForm.ConquestionServiceReference.IConquestionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConquestionServiceClient : System.ServiceModel.ClientBase<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.IConquestionService>, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.IConquestionService {
        
        public ConquestionServiceClient() {
        }
        
        public ConquestionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConquestionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConquestionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConquestionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player CreatePlayer(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player player) {
            return base.Channel.CreatePlayer(player);
        }
        
        public System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player> CreatePlayerAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player player) {
            return base.Channel.CreatePlayerAsync(player);
        }
        
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player RetrievePlayer(string name) {
            return base.Channel.RetrievePlayer(name);
        }
        
        public System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player> RetrievePlayerAsync(string name) {
            return base.Channel.RetrievePlayerAsync(name);
        }
        
        public void CreateGame(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            base.Channel.CreateGame(game);
        }
        
        public System.Threading.Tasks.Task CreateGameAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.CreateGameAsync(game);
        }
        
        public void CreateGame2(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, string questionSet, int noOfRounds) {
            base.Channel.CreateGame2(game, questionSet, noOfRounds);
        }
        
        public System.Threading.Tasks.Task CreateGame2Async(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, string questionSet, int noOfRounds) {
            return base.Channel.CreateGame2Async(game, questionSet, noOfRounds);
        }
        
        public void AddPlayer(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            base.Channel.AddPlayer(game);
        }
        
        public System.Threading.Tasks.Task AddPlayerAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.AddPlayerAsync(game);
        }
        
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game[] ActiveGames() {
            return base.Channel.ActiveGames();
        }
        
        public System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game[]> ActiveGamesAsync() {
            return base.Channel.ActiveGamesAsync();
        }
        
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game ChooseGame(string name, bool retrieveAssociation) {
            return base.Channel.ChooseGame(name, retrieveAssociation);
        }
        
        public System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game> ChooseGameAsync(string name, bool retrieveAssociation) {
            return base.Channel.ChooseGameAsync(name, retrieveAssociation);
        }
        
        public bool JoinGame(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.JoinGame(game);
        }
        
        public System.Threading.Tasks.Task<bool> JoinGameAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.JoinGameAsync(game);
        }
        
        public bool LeaveGame(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.LeaveGame(game);
        }
        
        public System.Threading.Tasks.Task<bool> LeaveGameAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.LeaveGameAsync(game);
        }
        
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player[] RetrieveAllPlayersByGameId(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.RetrieveAllPlayersByGameId(game);
        }
        
        public System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player[]> RetrieveAllPlayersByGameIdAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.RetrieveAllPlayersByGameIdAsync(game);
        }
        
        public bool StartGame(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.StartGame(game);
        }
        
        public System.Threading.Tasks.Task<bool> StartGameAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.StartGameAsync(game);
        }
        
        public void AddQuestionSet(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet questionSet) {
            base.Channel.AddQuestionSet(game, questionSet);
        }
        
        public System.Threading.Tasks.Task AddQuestionSetAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet questionSet) {
            return base.Channel.AddQuestionSetAsync(game, questionSet);
        }
        
        public bool CheckIfGameIsFinished(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.CheckIfGameIsFinished(game);
        }
        
        public System.Threading.Tasks.Task<bool> CheckIfGameIsFinishedAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.CheckIfGameIsFinishedAsync(game);
        }
        
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet[] RetrieveAllQuestionSets() {
            return base.Channel.RetrieveAllQuestionSets();
        }
        
        public System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet[]> RetrieveAllQuestionSetsAsync() {
            return base.Channel.RetrieveAllQuestionSetsAsync();
        }
        
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet RetrieveQuestionSet(int id) {
            return base.Channel.RetrieveQuestionSet(id);
        }
        
        public System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet> RetrieveQuestionSetAsync(int id) {
            return base.Channel.RetrieveQuestionSetAsync(id);
        }
        
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet RetrieveQuestionSetByTitle(string title) {
            return base.Channel.RetrieveQuestionSetByTitle(title);
        }
        
        public System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.QuestionSet> RetrieveQuestionSetByTitleAsync(string title) {
            return base.Channel.RetrieveQuestionSetByTitleAsync(title);
        }
        
        public bool ValidateAnswer(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Answer answer) {
            return base.Channel.ValidateAnswer(answer);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateAnswerAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Answer answer) {
            return base.Channel.ValidateAnswerAsync(answer);
        }
        
        public bool CheckPlayerAnswers(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round) {
            return base.Channel.CheckPlayerAnswers(game, round);
        }
        
        public System.Threading.Tasks.Task<bool> CheckPlayerAnswersAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round) {
            return base.Channel.CheckPlayerAnswersAsync(game, round);
        }
        
        public void SubmitAnswer(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.PlayerAnswer playerAnswer) {
            base.Channel.SubmitAnswer(round, playerAnswer);
        }
        
        public System.Threading.Tasks.Task SubmitAnswerAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.PlayerAnswer playerAnswer) {
            return base.Channel.SubmitAnswerAsync(round, playerAnswer);
        }
        
        public bool CheckIfAllPlayersAnswered(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round) {
            return base.Channel.CheckIfAllPlayersAnswered(game, round);
        }
        
        public System.Threading.Tasks.Task<bool> CheckIfAllPlayersAnsweredAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game, ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round) {
            return base.Channel.CheckIfAllPlayersAnsweredAsync(game, round);
        }
        
        public void CreateRound(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            base.Channel.CreateRound(game);
        }
        
        public System.Threading.Tasks.Task CreateRoundAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.CreateRoundAsync(game);
        }
        
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player GetRoundWinner(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round) {
            return base.Channel.GetRoundWinner(round);
        }
        
        public System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player> GetRoundWinnerAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Round round) {
            return base.Channel.GetRoundWinnerAsync(round);
        }
        
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Question GetRandomQuestion(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.GetRandomQuestion(game);
        }
        
        public System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Question> GetRandomQuestionAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.GetRandomQuestionAsync(game);
        }
        
        public ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player DetermineGameWinner(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.DetermineGameWinner(game);
        }
        
        public System.Threading.Tasks.Task<ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Player> DetermineGameWinnerAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.DetermineGameWinnerAsync(game);
        }
        
        public int DetermineNoOfCorrectAnswers(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.DetermineNoOfCorrectAnswers(game);
        }
        
        public System.Threading.Tasks.Task<int> DetermineNoOfCorrectAnswersAsync(ConquestionGame.Presentation.WinForm.ConquestionServiceReference.Game game) {
            return base.Channel.DetermineNoOfCorrectAnswersAsync(game);
        }
    }
}
